/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mario' at '17/02/16 01:27 AM' with Gradle 2.6
 *
 * @author mario, @date 17/02/16 01:27 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
